"""empty message

Revision ID: 2d4ac4832cba
Revises: 845ac5024295
Create Date: 2023-03-07 19:14:55.451926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4ac4832cba'
down_revision = '845ac5024295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant', sa.Column('recipientIndividual_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_grant_recipientIndividual_id'), 'grant', ['recipientIndividual_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grant_recipientIndividual_id'), table_name='grant')
    op.drop_column('grant', 'recipientIndividual_id')
    # ### end Alembic commands ###
