"""empty message

Revision ID: 845ac5024295
Revises: ab576a574929
Create Date: 2023-03-06 16:46:21.355815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845ac5024295'
down_revision = 'ab576a574929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant', sa.Column('insights_recipient_type', sa.String(length=255), nullable=False, server_default='Organisation'))
    op.alter_column('grant', 'recipientOrganization_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('grant', 'recipientOrganization_name',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.create_index(op.f('ix_grant_insights_recipient_type'), 'grant', ['insights_recipient_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grant_insights_recipient_type'), table_name='grant')
    op.alter_column('grant', 'recipientOrganization_name',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('grant', 'recipientOrganization_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('grant', 'insights_recipient_type')
    # ### end Alembic commands ###
